# 線虫のシミュレーションの設定
[setting]
alpha = -0.01 # 濃度勾配
x_peak = 4.5  # 勾配のピークのx座標 /cm
y_peak = 0    # 勾配のピークのy座標 /cm
dt = 0.01     # 時間刻みの幅 /s
T = 4.2       # 移動の1サイクルの継続時間 /s
f = 0.033     # 方向の平均周波数 /Hz
v = 0.022     # 線虫の速度 /cm/s
time = 250    # シミュレート時間 /s
tau = 0.1     # 時定数 /s
c_0 = 0.2     #ガウス関数の定数
lambda = 1.61 #ガウス関数の定数

# ニューロンアウトプット用の設定 "time = 10"が大事
[setting_newron_output]
alpha = -0.01    # 濃度勾配
x_peak = 4.5     # 勾配のピークのx座標 /cm
y_peak = 0       # 勾配のピークのy座標 /cm
dt = 0.01        # 時間刻みの幅 /s
T = 4.2          # 移動の1サイクルの継続時間 /s
f = 0.033        # 方向の平均周波数 /Hz
v = 0.022        # 線虫の速度 /cm/s
time = 10        # シミュレート時間 /s
tau = 0.1        # 時定数 /s
c_0 = 0.045      #ガウス関数の定数
lambda = 2.72938 #ガウス関数の定数
